config/routes.rb
Rails.application.routes.draw do
  get 'home', to: "home#index"
  get 'register', to: 'users#register'
  post 'auth', to: 'session#auth'
  get 'logout', to: 'session#logout'


  resources :users
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord::Base
  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  validates :name, presence: true, length: {minimum: 5, maximum: 128}
  validates :password, presence: true, length: {minimum: 10, maximum: 128}, format: { with: /^(?=.*[a-zA-Z])(?=.*[0-9]).{10,}$/}
  validates :email, presence: true, length: {maximum: 192}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/user.rb
class User < ApplicationRecord

  VALID_EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  VALID_PASSWORD_FORMAT = /^(?=.*[a-zA-Z])(?=.*[0-9]).{10,}$/

  validates :name, presence: true, length: {minimum: 5, maximum: 128}
  validates :password, presence: true, length: {minimum: 10, maximum: 128}
  validates :email, presence: true, length: {maximum: 192}

  # validate
  # validate

end

app/controllers/home_controller.rb
require 'net/http'
class HomeController < ApplicationController
  before_action :require_login

  def index
    binding.pry
    @user = User.new(session[:user])
    @ipInfo = request_infos
    render :index
  end

  def request_infos
    ActiveSupport::JSON.decode(
      Net::HTTP.get(
        URI("https://ipinfo.io/"+ request.remote_ip + "?token=" + ENV["IP_INFO_TOKEN"])
      )
    )
  end

  private
    def require_login
      redirect_to users_path unless session[:user_auth]
    end
end

app/controllers/session_controller.rb
require 'bcrypt'

class SessionController < ApplicationController
  before_action :set_user, only: %i[ auth ]

  def auth
    if user_params["email"].empty? || user_params["password"].empty?
      @errors = "Password or Email are empty"
      render template: "users/index", status: :unprocessable_entity
    else
      return if session[:user_auth]

      users = session[:users_list]
      user = user_exists?(users)
      binding.pry
      if user && @user.password == user[:password]
        session[:user_auth] = SecureRandom.base64(32)
        session[:user] = user
        redirect_to home_path
      else
      @errors = "Email or Password are invalid!!"
      render template: "users/index", status: :unprocessable_entity
      end
    end
  end

  def logout
    if session[:user_auth]
      session.delete(:user_auth)
      session.delete(:user)
    end
    redirect_to users_path
  end

  private
    def user_exists? users
      users = transform_to_object(users)
      return false if users.empty?
      users.each do |user|
        if user["email"].casecmp?(@user.email)
          return user
        end
      end
    end

    def transform_to_object users_text
      users = []
      users_text.each do |user|
        user_info = user.split(";")
        users.push(User.new(email: user_info[0], name: user_info[1], password: user_info[2]))
      end
      users
    end

    def set_user
      @user = User.new(user_params)
      @user.password = user_params[:password]
    end

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_session_users
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :is_authenticated

  # GET /users or /users.json
  def index
    self.setUser
    render :index
  end

  def register
    @user = User.new if !@user
    render :register
  end

  # GET /users/new
  def setUser
    @user = User.new if !@user
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]
    #Rails.cache.keys
    respond_to do |format|
      if @user && @user.valid?
        session[:users_list].push("#{@user.email};#{@user.name};#{@user.password}" )
        format.html { redirect_to users_path, notice: "User was successfully created." }
      else
        format.html { render :register, status: :unprocessable_entity }
      end
    end
  end


  private
    def verify_session_users
      unless session[:users_list]
        session[:users_list] = []
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    def is_authenticated
     if session[:user_auth]
      redirect_to home_path
     end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="location.svg"
          class="img-fluid" alt="Sample image">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <div class="mx-2">
          <h4 class="d-1">User Info </h4>
          <span> <%= @user.name %> </span> - <strong>  <%= @user.email %> </strong>
        </div>
        <table class="table mt-2">
          <tbody>
            <tr>
              <td><%= @ipInfo["city"]    %>   <i class="mx-1 bi bi-building"></i></td>
              <td><%= @ipInfo["region"]  %>   <i class="mx-1 bi bi-geo"></i></td>
              <td><%= @ipInfo["country"] %>   <i class="mx-1 bi bi-globe"></i></td>
            </tr>
          </tbody>
        </table>
        <div>
          <%= link_to "Sign Out", logout_path, class:"btn btn-primary mt-2", method: :post %>
        </div>
      </div>
    </div>
  </div>
<div class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
  <div class="text-white text-center w-100">
    Copyright © 2022. All rights reserved.
  </div>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title  itle>CoffeeBean</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_login.html.erb
<%= form_with(model:user, url: "/auth", method: :post) do |form| %>

  <div class="divider d-flex align-items-center my-4">
    <p class="text-center fw-bold mx-3 mb-0 display-4">Login</p>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control form-control-lg", placeholder:"Enter a valid email" %>
  </div>

  <div class="form-outline mb-3">
    <%= form.label :password %>
    <%= form.password_field  :password, class: "form-control form-control-lg", placeholder:"Enter a password"%>
  </div>

  <% if @errors %>
    <div class="mt-4 text-danger">
      <ul>
        <li><%= @errors %></li>
      </ul>
    </div>
  <% end %>

  <div class="d-flex justify-content-between align-items-center">
    <div class="form-check mb-0">
      <input class="form-check-input me-2" type="checkbox" value="" id="rememberMe" />
      <label class="form-check-label" for="rememberMe">
        Remember me
      </label>
    </div>
    <a href="#!" class="text-body">Forgot password?</a>
  </div>

  <div class="text-center text-lg-start mt-4 pt-2">
    <%= form.submit "Login", class: "btn btn-primary btn-lg pl-2 pr-2" %>
    <p class="small fw-bold mt-2 pt-1 mb-0">Already have account?
      <%= link_to "register", register_path %>
    </p>
  </div>

<% end %>

app/views/users/_register.html.erb
<%= form_with(model: user) do |form| %>
  <div class="divider d-flex align-items-center my-4">
    <p class="text-center fw-bold mx-3 mb-0 display-4">Register</p>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control form-control-lg", placeholder: "Enter a name" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control form-control-lg", placeholder:"Enter a valid email" %>
  </div>

  <div class="form-outline mb-3">
    <%= form.label :password %>
    <%= form.password_field  :password, class: "form-control form-control-lg", placeholder:"Enter a password"%>
  </div>

  <div class="d-flex justify-content-between align-items-center">
    <div class="form-check mb-0">
      <input class="form-check-input me-2" type="checkbox" value="" id="rememberMe" />
      <label class="form-check-label" for="rememberMe">
        Remember me
      </label>
    </div>
    <a href="#!" class="text-body">Forgot password?</a>
  </div>

  <% if user.errors.any? %>
    <div class="mt-4 text-danger">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center text-lg-start mt-4 pt-2">
    <%= form.submit class: "btn btn-primary btn-lg pl-2 pr-2" %>
    <p class="small fw-bold mt-2 pt-1 mb-0">Already have account?
      <%= link_to "Login", users_path  %>
    </p>
  </div>

<% end %>

app/views/users/index.html.erb
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
          class="img-fluid" alt="Sample image">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <%= render "users/login", user: @user %>
      </div>
    </div>
  </div>
  <div
    class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
    <div class="text-white w-100 text-center">
      Copyright © 2022. All rights reserved.
    </div>
  </div>
</section>

app/views/users/register.html.erb
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
          class="img-fluid" alt="Sample image">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <%= render "register", user: @user %>
      </div>
    </div>
  </div>
  <div class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
    <div class="text-white text-center w-100">
      Copyright © 2022. All rights reserved.
    </div>
  </div>
</section>